apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: paymentapi-deployment
spec:
  replicas: 3  
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: paymentapi
    spec:
      containers:
      - name: paymentapi
        image: payappcontainer.azurecr.io/paymentapi       
        ports:
        - containerPort: 80
        imagePullPolicy: Always   
