apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: paymentapi-deployment
spec: 
  minReadySeconds: 10
  replicas: 3
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: paymentapi
    spec: 
      containers: 
        - 
          image: payappcontainer.azurecr.io/paymentapi
          imagePullPolicy: Always
          name: paymentapi
          ports: 
            - 
              containerPort: 80
      imagePullSecrets: 
        - 
          name: payappsecret
